### ISSUE TITLE
New Wallet Setup `Continue Button` disabled

### ISSUE THREAD

**Issue by 0xJBass** [LightDotSo/LightDotSo#1657]
On new wallet creation continue & cancel button are disabled, despite having filled out all form fields.

**Screenshots**

![image](https://uploads.linear.app/7617f513-76a2-46a3-989e-9c59ba6aaba3/8049f42a-041b-411e-aa7d-34e4c449c33e/6b37b3a0-bccb-4c17-b9fe-864b83c4e59c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzc2MTdmNTEzLTc2YTItNDZhMy05ODllLTljNTliYTZhYWJhMy84MDQ5ZjQyYS0wNDFiLTQxMWUtYWE3ZC0zNGU0YzQ0OWMzM2UvNmIzN2IzYTAtYmNjYi00YzE3LWI5ZmUtODY0YjgzYzRlNTljIiwiaWF0IjoxNzA4MjA1NTg4LCJleHAiOjMzMjc4NzY1NTg4fQ.p1oug17UR9RYzYHSjcH0cirZG5NBpgmz6t1EFQztfuE)

**Comment by shunkakinoki** [comment]
Thank you so much!
