### ISSUE TITLE
token-icons library update

### ISSUE THREAD

**Issue by 0xa3k5** [LightDotSo/LightDotSo#2238]
hey, I've realized that LightDotSo is using `token-icons`, [here](https://github.com/LightDotSo/LightDotSo/blob/42e77fc81e561ace085c480df97ebd7f99f3f533/packages/elements/src/token-image.tsx#L156).

The repository's name has been updated to `web3icons`, because I'm going to expand the library to include more than `tokens`, (`networks` and `wallets` and more in the future) I was going to open a PR for it but I also realized the referenced path is for not-optimized svgs, wanted to flag that. 

The way it works, `@web3icons/core` package creates a `dist` folder with optimized svgs. However, I understand that you might not need to directly depend on the package and there is no API or hosted service for the optimized svgs. 

LMK If I can help in any way.

**Comment by shunkakinoki** [comment]
@0xa3k5 Thank you for this! Will update the URL accordingly, but since we're not loading the svgs (lazy calling them on the client), we won't have the capability to load your optimized svgs bundled. Regardless, I really appreciate the https://github.com/0xa3k5/web3icons and thank you for your contributions to the community!

**Comment by 0xa3k5** [comment]
thank you! Yeah that makes sense, if I can spare some time I'm thinking about building an api for this so I can host the optimized svgs, or maybe some other way. I'll open an issue/PR if necessary in the future. 

Awesome job on the light.so btw, amazing work!

**Comment by shunkakinoki** [comment]
That would be awesome!! Will be on hold for the API 🫡 Appreciate the awesome work 🙏

**Comment by 0xa3k5** [comment]
hey @shunkakinoki I've just updated the monorepo to host/serve the optimized svgs from the `core/svgs` path. You can just update the URL 

from: `https://raw.githubusercontent.com/0xa3k5/token-icons/main/packages/core/src/raw-svgs/tokens/branded/${token.symbol.toUpperCase()}.svg`

to: `https://raw.githubusercontent.com/0xa3k5/web3icons/main/packages/core/src/svgs/tokens/branded/${token.symbol.toUpperCase()}.svg`

you should be able to use the optimized svgs without changing much for now 😅

**Comment by shunkakinoki** [comment]
@0xa3k5 That's awesome!! Thank you so much for getting back to me - means a lot
Would you want to submit a PR for recognition or should I go ahead and implement it?
Appreciate the awesome work.
